### ISSUE TITLE
OneDrive destination

### ISSUE THREAD

**Issue by RoboMWM** [Ratismal/DriveBackup#1]
Would you consider an option to upload to OneDrive?

**Comment by Ratismal** [comment]
Potentially. I've finished implementing all of the features that were on my to-do list, so OneDrive support is coming next. However, I have not found any Java API for OneDrive, so it might take some time to figure something out.

**Comment by Ratismal** [comment]
It has been added!

**Comment by RoboMWM** [comment]
:o nice, will let you know how it works!
