### ISSUE TITLE
World/DIM1 is ignored when creating a backup

### ISSUE THREAD

**Issue by FeikoJoosten** [Ratismal/DriveBackup#12]
For some reason when creating a backup with the default settings the DIM1 folder located in the world folder is ignored. This is using spiggot 1.14.2.

**Comment by RoboMWM** [comment]
DIM1 is only used in vanilla. CB (and its derivatives like spigot) do not use this folder, and instead split up the dimensions into 3 separate world folders.

**Comment by FeikoJoosten** [comment]
Ah my mistake then!
