### ISSUE TITLE
Don't backup an empty server

### ISSUE THREAD

**Issue by RoboMWM** [Ratismal/DriveBackup#2]
I've currently been using [SimpleBackup](http://dev.bukkit.org/bukkit-plugins/simplebackup/) and for my Creative server, sometimes it won't be visited for an entire day - SimpleBackup skips the backup for this day.

**Comment by Ratismal** [comment]
Sounds good! I will work on this today.

**Comment by Ratismal** [comment]
This feature has been implemented and will be available in version 1.0.6.
How it works is as follows:
The plugin will not perform any backups until a player joins. If it does an update while there are no players on the server, it will stop doing subsequent backups until another player joins. This ensures that all changes made in between the last backup and the player leaving are still backed up.
