### ISSUE TITLE
Suggestion: Option to select saving method

### ISSUE THREAD

**Issue by Sqeegie** [Ratismal/DriveBackup#3]
Adding an option in the config to allow the end user to chose saving method would be an excellent addition to this plugin. For example, the user can select the option to only save locally, only remotely, or both. So say that the server owner is running off a limited disk size, and can't afford to use said space for backups. However, he has a large amount of unused space on his Google Drive, for example. He can select the option to only save the backups remotely to his Google Drive, therefore saving the valuable space on his local disk.

**Comment by RoboMWM** [comment]
Probably offtopic but

> running off a limited disk size

This is dangerous anyways, and can easily cause corruption if not rectified soon.

**Comment by Ratismal** [comment]
This has been implemented and will be available in version 1.0.7.
